sudo: false
language: node_js
cache:
  directories:
    - node_modules
node_js: 8
branches:
  only:
    - master
notifications:
  email: false
before_install:
  - npm update
install:
  - npm install
script:
  - npm run validate
after_success:
  - npm run report-coverage
  - npm run coveralls
